[package]
name = "rust-sentence-embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
candle-core = { version = "0.5.1", features = ["metal"] }
candle-nn = "0.5.1"
candle-transformers = "0.5.1"
hf-hub = { version = "0.3.2", features = ["tokio"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokenizers = "0.19.1"
